name = "email-moderation-production"
main = "src/index.ts"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
DEBUG_MODE = "false"
DISCORD_APPROVAL_CHANNEL_ID = "1458372243905187840"
DISCORD_ROUTE_APPROVAL_CHANNEL_ID = "1458920160424628305"
DISCORD_FEEDBACK_CHANNEL_ID = "1459470631379796113"

[[kv_namespaces]]
binding = "EMAIL_APPROVAL_KV"
id = "df97da21f82a45f58003899bd2D32cea"

[[kv_namespaces]]
binding = "ROUTE_APPROVAL_KV"
id = "911099e7bbe845e189cd7dfa4ff0ed72"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
